# Generated by Django 5.0.1 on 2024-02-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='Product',
        ),
    ]
