# Generated by Django 5.0.1 on 2024-02-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_remove_orders_product_orders_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='Product',
            new_name='product',
        ),
    ]
