# Generated by Django 5.0.1 on 2024-02-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_rename_product_carts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='product',
            new_name='Product',
        ),
    ]
